server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${BFF_MONGODB_URI:mongodb://localhost:27017}
      database: ${BFF_MONGODB_DATABASE:lina_local}

logging:
  level:
    com.lina: DEBUG
    org.springframework.web: DEBUG

lina:
  rag:
    base-url: ${ML_PIPELINE_BASE_URL:http://localhost:8000}
  auth-server:
    base-url: ${AUTH_SERVER_BASE_URL:http://localhost:8081}
